### PR TITLE
Fix ffmpeg 6 build

### LINKED ISSUE #9: Build broken on Noble (new ffmpeg version)
Jazzy and Rolling builds don't work right now because there is a new FFmpeg major version (6.x) but the Jammy version for Iron and Humble is 4.x.

For now the Noble builds have been marked not required for PR to merge - but we should come up with a solution so we can release this into Jazzy/Rolling

### PR DESCRIPTION
**Pull request by emersonknapp**
Closes #9

### CODE REVIEW

File: broll/src/frame_decoder.cpp [hunk 1]
```diff
@@ -14,6 +14,8 @@
 
 extern "C" {
 #include <libavcodec/avcodec.h>
+#include <libavcodec/bsf.h>
```
Comment (hrfuller) [inline broll/src/frame_decoder.cpp:17]: What symbols are included from this?

**Review by hrfuller — APPROVED** [review]

File: broll/src/frame_decoder.cpp (hunk 1 above)
Comment (emersonknapp) [reply broll/src/frame_decoder.cpp:17]: In 4.x almost nothing, but in 6.x `AVBitstreamFilter` is defined there instead of in the toplevel `avcodec.h`, but the header exists in both `libavcodec` versions so it's safe to include

**Comment by emersonknapp** [comment]
Jazzy isn't working because it's still just in `ros2-testing` apt repos, could patch up the images to fix it but whatever, will wait until it's actually released later this month to support it (just a release candidate right now)
